apiVersion: secretize/v1
kind: SecretGenerator
metadata:
  name: exec-env-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ../../../secretize
sources:
  - provider: env
    literals:
      - DATABASE_URL
      - API_KEY
      - newName=RENAMED_VAR
    kv:
      - CONFIG_JSON 