apiVersion: secretize/v1
kind: SecretGenerator
metadata:
  name: docker-vault-secrets
  annotations:
    config.kubernetes.io/function: |
      container:
        image: secretize:local
        envs:
          - DATABASE_URL
          - API_KEY
          - JWT_SECRET
          - CONFIG_JSON
sources:
  - provider: env
    literals:
      - DATABASE_URL
      - API_KEY
      - JWT_SECRET
    kv:
      - CONFIG_JSON 
