apiVersion: secretize/v1
kind: SecretGenerator
metadata:
  name: docker-vault-secrets
  annotations:
    config.kubernetes.io/function: |
      container:
        image: secretize:local
        network: true
        envs:
          - VAULT_ADDR
          - VAULT_TOKEN
sources:
  - provider: hashicorp-vault
    literals:
      # Single secret values from docker-app namespace
      - DATABASE_URL=secret/data/data/docker-app/database-url:value
      - API_KEY=secret/data/data/docker-app/api-key:value
      - JWT_SECRET=secret/data/data/docker-app/jwt-secret:value
    kv:
      # KV secrets with all key-value pairs
      - secret/data/data/docker-app/app-config
      - secret/data/data/docker-app/feature-flags
