on: push
name: CI
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.26

      - name: test
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make test

      - name: publish code coverage results
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}